name: webgpu_interop
description: dart js_interop for web applications. This library is created directly from WebIDL.
version: 0.9.1
repository: https://github.com/munrocket/webgpu-interop

environment:
  sdk: ^3.5.4

dependencies:
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  fetch_api: ^2.2.0
  lints: ^4.0.0
  vector_math: ^2.1.4
