name: webgpu_interop
description: Dart interop for web applications
version: 0.9.0
repository: https://github.com/munrocket/webgpu-interop

environment:
  sdk: ^3.5.4

dependencies:
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  lints: ^4.0.0
  test: ^1.24.0
